---
title: "Week 5 Discussion"
author: "Peter Gatica"
date: "`09/24/2022`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(matlib)
```

```{r}
# Function to calculate the probability of rolling the same number on each die.
# d = number of dice being rolled
# s = number of sides of each die
# r = number of rolls to attempt

# 1/s^d = probability of rolling a 6 on each dice (d) on a 6 sided die (s)
# 1 - (1/s^d) = probability of not rolling a 6 on each dice (d) on a 6 sided 
# die (s)
# 1 - (1 - (1/s^d))^r of rolling the same number on each s sided die after 
# rolling r number of times.

roll_prob <- function(d, s, r){
  1 - (1 - (1/s^d))^r
}
```

```{r}
n_dice <- 3
n_die_sides <- 6
```

```{r}
n_rolls <- 1

roll_prob(n_dice,n_die_sides,n_rolls)
```

```{r}
n_rolls <- 10

roll_prob(n_dice,n_die_sides,n_rolls)
```

```{r}
n_rolls <- 100

roll_prob(n_dice,n_die_sides,n_rolls)
```

```{r}
n_rolls <- 149

roll_prob(n_dice,n_die_sides,n_rolls)
```

```{r}
n_rolls <- 150

roll_prob(n_dice,n_die_sides,n_rolls)
```

