---
title: "HW Assignment 3 - Data605 Fall 2022 - Dr. Fulton"
author: "Peter Gatica"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
Sys.setenv(RGL_USE_NULL=TRUE)
library(matlib)
library(pracma)
library(tinytex)
library(matrixcalc)
```
$$
\text{ASSIGNMENT 3}
\\ \\
$$
$$
\text{IS 605 FUNDAMENTALS OF COMPUTATIONAL MATHEMATICS - 2015}
$$

Problem set 1

$$
(1)\ What\ is\ the\ rank\ of\ the\ matrix\ A?
\\
A\ = \ \begin{bmatrix}1&2&3&4\\ -1&0&1&3\\ 0&1&-2&1\\ 5&4&-2&-3\end{bmatrix}
\\
\\
$$

```{r}
A <- matrix(c(1,2,3,4,-1,0,1,3,0,1,-2,1,5,4,-2,-3), nrow=4, ncol=4)
rref(A)
```

$$
\\
Answer:\ With\ the\ n\ =\ 4\ columns\ and\ r\ =\ 4\ non-zero\ rows,
\\ rank\ of\ the\ matrix\ r(A)\ =\ 4. 
\\
$$

$$
(2)\ Given\ an\ m*n\ matrix\ where\ m > n,\ 
what\ can\ be\ the\ maximum\ rank?
\\ The\ minimum\ rank, assuming\ that\ the\ matrix\ is\ nonzero?
$$
$$
Answer:\ r(A)\ <=\ min(m,n)\ so\ if\ m>n\ then\ maximum\ r(A)\ <= n.\ Minimum\ r(A)\ =\ 1.
\\
$$
$$
(3)\ What\ is\ the\ rank\ of\ matrix\ B?
\\ 
B\ = \ \begin{bmatrix}1&2&1\\ 3&6&3\\ 2&4&2\end{bmatrix}
\\ 
$$
```{r}
B <- matrix(c(1,3,2,2,6,4,1,3,2), nrow=3, ncol=3)
rref(B)
```
$$
Answer:\ Since\ there\ is\ only\ one\ nonzero\ row,\ r(B)\ =\ 1.
$$
Problem set 2

$$
Compute\ the\ eigenvalues\ and\ eigenvectors\ of\ the\ matrix\ A. \ You’ll\ need\ to\ show\ your\ work.
\\ You’ll\ need\ to\ write\ out\ the\ characteristic\ polynomial\ and\ show\ your\ solution.
\\
A\ = \ \begin{bmatrix}1&2&3\\ 0&4&5\\ 0&0&6\end{bmatrix}
\\
$$

```{r}
(A <- matrix(c(1,0,0,2,4,0,3,5,6), nrow=3, ncol=3))
eigen(A)$values
```

$$
The\ eigenvalues\ of\ an\ upper\ or\ lower\ triangular\ matrix\ are\ the\ diagonal\ entries\ of\ the\ matrix.
\\ The\ eigenvalues\ of\ matrix\ A\ are\ 1,\ 4\ and\ 6.
\\
$$
$$
The\  characteristic\  polynomial\  is\\
p_{A}(x)\  =\ x^{3}-11x^{2}+34x-24\ = (x-1)(x-4)(x-6)
$$
$$
Each\  eigenvalue\  appears\  once\ in\  the\  characteristic\  polynomial\\
  \alpha_{A} =(1)\ ,\  \alpha_{A} =(4)\,   \alpha_{A} =(6)\
$$
$$
Eigenspaces
$$
$$
\\
\\
\lambda =1\\
A-(1)I_{3}\  =\  \begin{bmatrix}1-1&2&3\\ 0&4-1&5\\ 0&0&6-1\end{bmatrix} =\begin{bmatrix}0&2&3\\ 0&3&5\\ 0&0&5\end{bmatrix} \underrightarrow{RREF} \  \begin{bmatrix}0&1&0\\ 0&0&1\\ 0&0&0\end{bmatrix} 
\\
$$
$$
\\
E_{A}(1)=N(A-(1))I_{3}=\left< \left\{ \begin{bmatrix}0\\ 1\\ 1\end{bmatrix} \right\}  \right>  
$$

```{r}
(A1 <- matrix(c(0,0,0,2,3,0,3,5,5), nrow=3, ncol=3))
rref(A -1 * diag(3))
```

$$
\\
\lambda =4
\\  A-(4)I_{3}\  =\  \begin{bmatrix}1-4&2&3\\ 0&4-4&5\\ 0&0&6-4\end{bmatrix} =\begin{bmatrix}-3&2&3\\ 0&0&5\\ 0&0&2\end{bmatrix} \underrightarrow{RREF} \  \begin{bmatrix}1&-2/3&0\\ 0&0&1\\ 0&0&0\end{bmatrix} 
\\
$$

$$
\\
E_{A}(4)=N(A-(4))I_{3}=\left< \left\{ \begin{bmatrix}\frac{2}{3} \\ 1 \\1 \end{bmatrix} \right\}  \right> = \left< \left\{ \begin{bmatrix} 2 \\ 3 \\ 3\end{bmatrix} \right\}  \right>   
$$

```{r}
(A4 <- matrix(c(-3,0,0,2,0,0,3,5,2), nrow=3, ncol=3))
rref(A -4 * diag(3))
```
$$
\\
\lambda =6
\\  A-(6)I_{3}\  =\  \begin{bmatrix}1-6&2&3\\ 0&4-6&5\\ 0&0&6-6\end{bmatrix} =\begin{bmatrix}-5&2&3\\ 0&-2&5\\ 0&0&0\end{bmatrix} \underrightarrow{RREF} \  \begin{bmatrix}1&0&-1.6\\ 0&1&-2.5\\ 0&0&0\end{bmatrix} 
\\
$$

$$
\\
E_{A}(6)=N(A-(6))I_{3}=\left< \left\{ \begin{bmatrix} 1.6 \\2.5 \\ 1\end{bmatrix} \right\}  \right>=\left< \left\{ \begin{bmatrix} 8/5 \\5/2 \\ 1\end{bmatrix} \right\}  \right>
$$

```{r}
(A6 <- matrix(c(-5,0,0,2,-2,0,3,5,0), nrow=3, ncol=3))
rref(A6)
rref(A -6 * diag(3))
b <- c(0,0,0)
# Solve(A6,b, verbose=TRUE)
echelon((A - 6 * diag(3)), b, reduced=TRUE, verbose=TRUE, fractions=TRUE)
```

