---
title: "EigenShoes - DATA605 Assignment 4"
author: "Peter Gatica"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

Sys.setenv(RGL_USE_NULL=TRUE)
library(OpenImageR)
library(doParallel)
library(foreach)
library(jpeg)
library(EBImage)
```

```{r}
#Here we add graphics to the data set.
# set counter limit to 17
num = 17

# read jpegs into files list
(files = list.files('/Users/Audiorunner13/CUNY MSDS Course Work/DATA605 Fall 2022/Week 4/jpg/',pattern="\\.jpg")[1:num])
```

View Shoes Function plot_jpeg
```{r}
# Set Adjustment Parameters
height = 1200; width = 2500; scale = 20

plot_jpeg = function(path, add = FALSE)
  { jpg = readJPEG(path,native = T)  # read the file 
  res = dim(jpg)[2:1]  # get the resolution, [x,y]
  if (!add) # initialize an empty plot area if add == FALSE
    plot(1,1,xlim = c(1,res[1]),ylim = c(1,res[2]),asp=1, type = 'n', xaxs='i',yaxs='i',xaxt='n',yaxt='n',xlab='',ylab='',bty='n')
  rasterImage(jpg,1,1,res[1],res[2])
  }
```

Loads data into an array
```{r}
#  Load array
im=array(rep(0,length(files)*height/scale*width/scale*3), dim=c(length(files), height/scale, width/scale,3))

for (i in 1:17){
temp=resize(readJPEG(paste0("/Users/Audiorunner13/CUNY MSDS Course Work/DATA605 Fall 2022/Week 4/jpg/",files[i])),height/scale, width/scale)

im[i,,,]=array(temp,dim=c(1, height/scale, width/scale,3))
}
```

Vectorize

```{r}
flat=matrix(0,17,prod(dim(im)))

for (i in 1:17) {
  newim <- readJPEG(paste0("/Users/Audiorunner13/CUNY MSDS Course Work/DATA605 Fall 2022/Week 4/jpg/",files[1]))
  
  r=as.vector(im[i,,,1]); g=as.vector(im[1,,,2]);b=as.vector(im[1,,,3]) 
  
  flat[i,] <- t(c(r,g,b))
}

shoes=as.data.frame(t(flat))
```

Actual Plots of images

```{r}
# Old shoes
par(mfrow=c(3,3))
par(mai=c(.3,.3,.3,.3))

for (i in 1:17){
  plot_jpeg(writeJPEG(im[i,,,]))
}
```

```{r}
# Eigencomponents from correlation structure
scaled = scale(shoes, center = TRUE, scale = TRUE)
mean.shoe=attr(scaled, "scaled:center")  # saving for classification
std.shoe=attr(scaled, "scaled:scale")  # saving for classification...later
# scaled[is.na(scaled)] = 0
```

Calculate the Covariance(Correlation)

```{r}
Sigma_=cor(scaled)
```

Get the Eigencomponents
```{r}
myeigen=eigen(Sigma_)
cumsum(myeigen$values)/ sum(myeigen$values)
```

Eigenshoes

```{r}
scaling=diag(myeigen$values[1:4]^(-1/2)) / (sqrt(nrow(scaled)-1))

eigenshoes=scaled %*% myeigen$vectors[,1:4] %*% scaling

par(mfrow=c(2,3))

imageShow(array(eigenshoes[,1], c(60,125,3)))
# imageShow(array(eigenshoes[,2], c(60,125,3)))
```


Generate Principal Components
Transform the images.

```{r}
height=1200
width=2500
scales=20
newdata=im
dim(newdata) = c(length(files),height * width * 3 / scale^2)
mypca = princomp(t(as.matrix(newdata)), scores = TRUE, cor=TRUE)
```

Eigenshoes
Generate Eigenshoes
```{r}
mypca2 = t(mypca$scores)
dim(mypca2) = c(length(files),height/scale, width/scale, 3)
par(mfrow = c(5,5))
par(mai = c(.001, .001, .001, .001))

for (i in 1:17){ #plot the first 17 Eigenshoes only
  plot_jpeg(writeJPEG(mypca2[i,,,], bg="white")) # complete without reduction
  }
```

```{r}
a = round(mypca$sdev[1:17]^2 / sum(mypca$sdev^2), 3)
cumsum(a)
```

