---
title: "DATA 605 Assignment Week 14"
author: "Peter Gatica"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(pracma)
```

### ASSIGNMENT 14 - TAYLOR SERIES
#### IS 605 FUNDAMENTALS OF COMPUTATIONAL MATHEMATICS - 2021
##### This week, we’ll work out some Taylor Series expansions of popular functions.

$$ f\left( x\right)  =\frac{1}{\left( 1-x\right)  } $$
Derative:

$$ f\left( x\right)  =\  \sum^{\infty }_{n=0} \frac{{}f^{(n)}\left( a\right)  }{n!} \left( x-a\right)^{n}  $$
```{r}
tylr_ser = function(x) {1/(1-x)}
(p_solution = taylor(tylr_ser, x0 = 0, n = 4))
```
$$ f\left( x\right)  =e^{x} $$
Derivatives:
$$ f\left( x\right)  =e^{x};f(0)=1 $$
$$ f^{\prime }\left( x\right)  =e^{x};f^{\prime }(0)=1 $$
$$ f^{\prime \prime }\left( x\right)  =e^{x};f^{\prime \prime }(0)=1 $$
$$ f^{\prime \prime \prime }\left( x\right)  =e^{x};f^{\prime \prime \prime }(0)=1 $$
$$ f^{(4)}=e^{x};f^{(4)}(0)=1 $$
```{r}
tylr_ser = function(x) {exp(x)}
(p_solution = taylor(tylr_ser, x0 = 0, n = 4))
```
$$ f(x)=ln(1+x) $$
Derivatives
$$ f(x)=ln\frac{1}{1+x} ;f^{\prime }(0)=1 $$
$$ f^{\prime \prime }(x)=\frac{-1}{(1+x)^{2}} ;f^{\prime \prime }(0)=-1 $$
$$ f^{\prime \prime \prime }(x)=\frac{2}{(1+x)^{3}} ;f^{\prime \prime^{\prime } }(0)=2 $$
$$ f^{(4)}(x)=\frac{-6}{(1+x)^{4}} ;f^{(4)}(0)=-6 $$
```{r}
tylr_ser = function(x) {log(1+x)}
(p_solution = taylor(tylr_ser, x0 = 0, n = 4))
```
$$ f(x)=x^{\left( \frac{1}{2} \right)  } $$
```{r}
tylr_ser = function(x) {(x^1/2)}
(p_solution = taylor(tylr_ser, x0 = 0, n = 4))
```

